school:
  name: school1
  address: zaliznuj_street

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration, classpath:db/scripts
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    ddl-auto: create-drop
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect


  config:
    use-legacy-processing: true