school:
  name: school1
  address: zaliznuj_street

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration, classpath:db/scripts
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    ddl-auto: create-drop
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: create.sql

  config:
    use-legacy-processing: true