info:
  ua-info: "good weather"

server:
  shutdown: "graceful"
school:
  name: school1
  address: zaliznuj_street

spring:
  lifecycle:
    timeout-per-shutdown-phase: "20s"
  flyway:
    enabled: true
    locations: classpath:db/migration, classpath:db/scripts
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    ddl-auto: create-drop
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect

  config:
    use-legacy-processing: true

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    db:
      enabled: true
    diskspace:
      enabled: true
    ping:
      enabled: true
    defaults:
      enabled: false
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true
    health:
      show-details: always
      show-components: always
      defaults:
        enabled: true
      probes:
        enabled: true
